name: Algolia Index Update

on:
  push:
    branches:
      - main

jobs:
  update_algolia_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack (for Yarn 4)
        run: corepack enable

      - name: Install dependencies with Yarn PnP
        run: yarn install --immutable

      - name: Update Algolia Index
        run: yarn node upload-to-algolia.mjs
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
