name: Algolia Index Update

on:
  push:
    branches:
      - main

jobs:
  update_algolia_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn --immutable

      - name: Update Algolia Index
        run: node upload-to-algolia.js
        env:
            ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
            ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
